language: perl
perl:
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"
matrix:
  include:
    - perl: "5.8.1"
      install:
        - cpanm -n --force "File::Spec"
        - cpanm -n "Test::Fatal" "Test::More" "Test::Warnings"
        - cpanm "B::Hooks::EndOfScope" "Lexical::SealRequireHints"
    - perl: "5.8.3"
      install:
        - cpanm -n --force "File::Spec"
        - cpanm -n "Test::Fatal" "Test::More" "Test::Warnings"
        - cpanm "B::Hooks::EndOfScope" "Lexical::SealRequireHints"
    - perl: "5.8.9"
      install:
        - cpanm -n "Test::Fatal" "Test::More" "Test::Warnings"
        - cpanm "B::Hooks::EndOfScope" "Lexical::SealRequireHints"
    - perl: "5.10"
      install:
        - cpanm -n "Test::Fatal" "Test::More" "Test::Warnings"
        - cpanm "B::Hooks::EndOfScope" "Lexical::SealRequireHints"
before_install:
  - "source devel.travis/travis-perlbrew"
  - "perlbrew install-cpanm -f"
  - "perl -V"
install:
  - cpanm -n "Test::Fatal" "Test::More" "Test::Warnings"
  - cpanm "B::Hooks::EndOfScope"
script:
  - HARNESS_IS_VERBOSE=1 prove -Iinc -Ilib t
