language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"
matrix:
  include:
    - perl: "5.8.3"
      install:
        - cpanm "B::Hooks::EndOfScope" "Test::Fatal" "Test::More" "Test::Warnings"
        - cpanm http://cpan.metacpan.org/authors/id/C/CH/CHOCOLATE/Devel-Pragma-0.54.tar.gz
    - perl: "5.8.9"
      install:
        - cpanm "B::Hooks::EndOfScope" "Test::Fatal" "Test::More" "Test::Warnings"
        - cpanm http://cpan.metacpan.org/authors/id/C/CH/CHOCOLATE/Devel-Pragma-0.54.tar.gz
before_install:
  - "source devel.travis/travis-perlbrew"
  - "perlbrew install-cpanm -f"
  - "perl -V"
install:
  - cpanm "B::Hooks::EndOfScope" "Test::Fatal" "Test::More" "Test::Warnings"
script:
  - HARNESS_IS_VERBOSE=1 prove -Iinc -Ilib t
