# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`warnings-MaybeFatal`
	:runtime-requirement    [ :on "perl 5.008001"^^:CpanId ];
	:runtime-requirement    [ :on "B::Hooks::EndOfScope"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:test-requirement       [ :on "Test::Fatal"^^:CpanId ];
	:test-requirement       [ :on "Test::Warnings"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

